name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0-dev.2198+e5f5229fd
        use-cache: false

    - name: Run fmt
      run: zig fmt --check **/*.zig

  test:
    needs: fmt
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x86_64
            target: x86_64-linux
          - os: windows-latest
            name: Windows x86_64
            target: x86_64-windows
          - os: macos-13
            name: macOs x86_64
            target: x86_64-macos
          - os: macos-14
            name: macOs Arm64
            target: aarch64-macos
          - os: ubuntu-latest
            name: Linux Arm64
            target: aarch64-linux
            qemu-platform: arm64

    name: ${{ matrix.name }}
    timeout-minutes: 15
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0-dev.2198+e5f5229fd
        use-cache: false

    - name: Setup QEMU
      if: matrix.qemu-platform != ''
      uses: docker/setup-qemu-action@v1

    - name: Run tests
      run: zig build test -Dtarget=${{ matrix.target }}${{ matrix.qemu-platform != '' && ' -fqemu' || '' }} --summary all --verbose
